### ISSUE TITLE
代码什么时候发布

### ISSUE THREAD

**Issue by baosir529a** [xlxwalex/ABSA-Scope#1]
你好什么时候可以发布代码

**Comment by xlxwalex** [comment]
你好，

感谢关注我们的工作。目前我们仅计划对标注数据集进行开源，没有整理该工作代码的时间和计划。

但如果你对实现细节或在复现工作时遇到任何问题，欢迎邮件 [xlxw@zju.edu.cn](mailto:xlxw@zju.edu.com)联系！
